config:
  backup: false
  banner: false
  create: true
  diff_command: delta --file-style omit {0} {1}
  dotpath: src
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: true
  showdiff: true
dotfiles:
  f_bash_logout:
    src: bash_logout
    dst: ~/.bash_logout
    chmod: '644'
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
    chmod: '644'
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  f_bin_dotdrop:
    src: bin/dotdrop
    dst: ~/bin/dotdrop
    chmod: '755'
    actions:
    - ln ~/bin/dotdrop .drop
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    chmod: '644'
  f_profile:
    src: profile
    dst: ~/.profile
    chmod: '755'
profiles:
  oak:
    dotfiles:
    - ALL
  eucalyptus:
    dotfiles:
    - ALL
  pawpaw:
    dotfiles:
    - ALL
actions:
  post:
    ln: cd $(dirname {0}) && ln --force --symbolic $(basename {0}) {1}
