#!/usr/bin/env sh


# Universal variables

export PATH="${HOME}/.cargo/bin:${HOME}/bin:${PATH}:/srv/bin"

editor="vis"
command -v ${editor} > /dev/null \
&& export EDITOR="${editor}" \
&& export VISUAL="${editor}"

# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="${HOME}/.cache"


# Command-specific variables

command -v fd > /dev/null \
&& export FZF_DEFAULT_COMMAND="fd --type file --hidden --follow --exclude .git"

export STARSHIP_CACHE="/tmp/starship"

export ASDF_NPM_DEFAULT_PACKAGES_FILE="${HOME}/.config/asdf/default-npm-packages"


# ENV command - loads on every interactive shell invocation
shellrc="${HOME}/.config/dash/dashrc"
test -f "${shellrc}" \
&& export ENV="${shellrc}"


on_logout=

on_logout() {
  test -n "${on_logout}" \
  && on_logout="${on_logout}; "

  on_logout="${on_logout}${@}"
}


# Run pulseaudio for the duration of the login session
if command -v pulseaudio > /dev/null; then
  pulseaudio --check \
  && pulseaudio --kill

  pulseaudio --exit-idle-time=-1 --start

  on_logout "pulseaudio --check && pulseaudio --kill"
fi


# Run music player for the duration of the login session
if command -v mpd > /dev/null; then
  pid="${HOME}/.config/mpd/pid"

  test ! -s "${pid}" \
  && mpd

  on_logout "test -s \"${pid}\" && mpd --kill"
fi


test -n "${on_logout}" \
&& trap "${on_logout}" EXIT
