#!/usr/bin/env sh


# Universal variables

export PATH="${HOME}/.cargo/bin:${HOME}/bin:${PATH}:/srv/bin"

editor="vis"
command -v ${editor} > /dev/null \
&& export EDITOR="${editor}" \
&& export VISUAL="${editor}"


# Command-specific variables

command -v fd > /dev/null \
&& export FZF_DEFAULT_COMMAND="fd --type file --hidden --follow --exclude .git"

export STARSHIP_CACHE="/tmp/starship"

export ASDF_NPM_DEFAULT_PACKAGES_FILE="${HOME}/.config/asdf/default-npm-packages"


# ENV command - loads on every interactive shell invocation
shellrc="${HOME}/.config/dash/dashrc"
test -f "${shellrc}" \
&& export ENV="${shellrc}"


# Run pulseaudio for the duration of the login session
command -v pulseaudio > /dev/null \
&& pulseaudio --exit-idle-time=-1 --start \
&& trap "pulseaudio --kill" EXIT
