#!/usr/bin/env sh


bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width           2
bspc config window_gap             36


#bspc config split_ratio            0.52
bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true


bspc config focus_follows_pointer  true


#bspc rule -a Gimp desktop='8' follow=on state=floating
#bspc rule -a Gimp follow=on state=floating
#bspc rule -a Chromium desktop='2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a xst-256color_launcher center=on focus=on state=floating sticky=on
#bspc rule -a Firefox desktop='2' follow=on state=floating
#bspc rule -a KeePassXC desktop='0' state=tiled


bspc config presel_feedback_color "#757575"
